-- Create meal_plans table
CREATE TABLE IF NOT EXISTS public.meal_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Create index for efficient user queries
CREATE INDEX IF NOT EXISTS idx_meal_plans_user_id ON public.meal_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_meal_plans_user_dates ON public.meal_plans(user_id, start_date DESC);

-- Create planned_meals table
CREATE TABLE IF NOT EXISTS public.planned_meals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_plan_id bigint NOT NULL REFERENCES public.meal_plans(id) ON DELETE CASCADE,
  meal_id bigint NOT NULL REFERENCES public.meals(id) ON DELETE CASCADE,
  planned_for_date date NOT NULL,
  meal_type text NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner')),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_planned_meals_plan_id ON public.planned_meals(meal_plan_id);
CREATE INDEX IF NOT EXISTS idx_planned_meals_meal_id ON public.planned_meals(meal_id);
CREATE INDEX IF NOT EXISTS idx_planned_meals_date ON public.planned_meals(planned_for_date);

-- Enable Row Level Security
ALTER TABLE public.meal_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planned_meals ENABLE ROW LEVEL SECURITY;

-- RLS Policies for meal_plans
CREATE POLICY "Users can view their own meal plans"
  ON public.meal_plans
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own meal plans"
  ON public.meal_plans
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own meal plans"
  ON public.meal_plans
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own meal plans"
  ON public.meal_plans
  FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for planned_meals
CREATE POLICY "Users can view their own planned meals"
  ON public.planned_meals
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.meal_plans
      WHERE meal_plans.id = planned_meals.meal_plan_id
      AND meal_plans.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert their own planned meals"
  ON public.planned_meals
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.meal_plans
      WHERE meal_plans.id = planned_meals.meal_plan_id
      AND meal_plans.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their own planned meals"
  ON public.planned_meals
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.meal_plans
      WHERE meal_plans.id = planned_meals.meal_plan_id
      AND meal_plans.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete their own planned meals"
  ON public.planned_meals
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.meal_plans
      WHERE meal_plans.id = planned_meals.meal_plan_id
      AND meal_plans.user_id = auth.uid()
    )
  );
