-- Create meals table
-- Based on architecture.md schema definition

begin;

-- Create meals table
create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  meal_type text not null,
  description text,
  image_url text,
  source_url text,
  ingredients text,
  instructions text,
  rating smallint check (rating >= 1 and rating <= 5),
  dietary_tags text[],
  created_at timestamptz default now()
);

-- Create index on user_id for efficient queries
create index if not exists idx_meals_user_id on public.meals(user_id);

-- Enable Row Level Security
alter table public.meals enable row level security;

-- Create RLS policies
create policy "Users can view their own meals"
  on public.meals for select
  using (auth.uid() = user_id);

create policy "Users can insert their own meals"
  on public.meals for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own meals"
  on public.meals for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own meals"
  on public.meals for delete
  using (auth.uid() = user_id);

commit;
