-- Migration: Create user_staples table for pantry inventory management
-- Story 3.15: Pantry Inventory / "Have it" Check

begin;

-- Create user_staples table to store user's pantry staple ingredients
CREATE TABLE IF NOT EXISTS public.user_staples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  ingredient_text text NOT NULL,
  category text DEFAULT 'other' CHECK (category IN ('spices', 'oils', 'grains', 'dairy', 'condiments', 'other')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (user_id, ingredient_text)
);

-- Create index for faster lookups by user_id
CREATE INDEX IF NOT EXISTS idx_user_staples_user_id ON public.user_staples(user_id);

-- Enable Row Level Security
ALTER TABLE public.user_staples ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only access their own staples
CREATE POLICY "Users can view their own staples"
  ON public.user_staples
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own staples"
  ON public.user_staples
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own staples"
  ON public.user_staples
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own staples"
  ON public.user_staples
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto-updating updated_at
DROP TRIGGER IF EXISTS set_user_staples_updated_at ON public.user_staples;
CREATE TRIGGER set_user_staples_updated_at
  BEFORE UPDATE ON public.user_staples
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- Add comment for documentation
COMMENT ON TABLE public.user_staples IS 'Stores user pantry staple ingredients that are automatically marked as "already have" in shopping lists';

commit;
