-- Create recommendation_dismissals table
-- Story 3.18: Recommended Meals Based on Similar Users
-- Tracks meals that users have dismissed from recommendations

BEGIN;

-- Create recommendation_dismissals table
CREATE TABLE IF NOT EXISTS public.recommendation_dismissals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  meal_name TEXT NOT NULL,
  dismissed_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 days'),
  UNIQUE(user_id, meal_name)
);

-- Create index for efficient queries
CREATE INDEX IF NOT EXISTS idx_recommendation_dismissals_user_id 
  ON public.recommendation_dismissals(user_id);

CREATE INDEX IF NOT EXISTS idx_recommendation_dismissals_expires_at 
  ON public.recommendation_dismissals(expires_at);

-- Enable Row Level Security
ALTER TABLE public.recommendation_dismissals ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own dismissals"
  ON public.recommendation_dismissals FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own dismissals"
  ON public.recommendation_dismissals FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own dismissals"
  ON public.recommendation_dismissals FOR DELETE
  USING (auth.uid() = user_id);

COMMIT;
